apiVersion:  v1
kind:  ConfigMap
metadata:
  name:  k8s-sample-app-config
data:
  APP_NAME: k8s-sample-app
  PORT: "3000"
  RACK_ENV: production
  MYSQL_USER: root
  MYSQL_DATABASE: k8s_sample_app_production
