apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-sample-app-web
  labels:
    app.kubernetes.io/name: k8s-sample-app-web
  # namespace: pyroscope
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app-web
  labels:
    app.kubernetes.io/name: k8s-sample-app-web
spec:
  type: ClusterIP
  ports:
    - port: 4040
      targetPort: api
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: k8s-sample-app-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-app-web
  labels:
    app.kubernetes.io/name: k8s-sample-app-web
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-sample-app-web
  strategy:
    type: RollingUpdate # default value, but explicitly set for demo
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-sample-app-web
    spec:
      serviceAccountName: k8s-sample-app-web
      imagePullSecrets:
      - name: dockerhub-credentials
      initContainers:
        - name: k8s-sample-app-web-migrate
          image: rperry2174/ruby_rails_docker:{{GIT_TAG}}
          args: ["bundle", "exec", "rake", "db:create", "db:migrate", "db:seed"]

          env:
            - name: ABALONE_DATABASE_HOSTNAME
              value: postgresql-web
          # envFrom: &envfrom1
          #   - configMapRef:
          #       name: k8s-sample-app-config
        # env: &env1
            # - name: SECRET_KEY_BASE
            #   valueFrom:
            #     secretKeyRef:
            #       name: k8s-sample-app-secrets
            #       key: secret_key_base
          # - name: ABALONE_DATABASE_HOSTNAME
          #   value: postgresql
            # - name: MYSQL_PW
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-pass
            #       key: password
      containers:
        - name: k8s-sample-app-web
          image: rperry2174/ruby_rails_docker::{{GIT_TAG}}
          args: ["bundle", "exec", "rails", "s"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ABALONE_DATABASE_HOSTNAME
              value: postgresql-web
          ports:
            - containerPort: 3000
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
          # envFrom: *envfrom1
      # containers:
      #   - name: k8s-sample-app-web
      #     image: rperry2174/ruby_rails_docker:{{GIT_TAG}}
      #     args: ["bundle", "exec", "rails", "server", "-p", "3000"]
          # resources:
          #   requests:
          #     cpu: 200m
          #     memory: 200Mi
          # ports:
          #   - containerPort: 3000
      #     livenessProbe:
      #       httpGet:
      #         path: /
      #         port: 3000
      #       initialDelaySeconds: 5
      #       timeoutSeconds: 1
      #     readinessProbe:
      #       httpGet:
      #         path: /
      #         port: 3000
      #       initialDelaySeconds: 5
      #       timeoutSeconds: 1
      #     envFrom: *envfrom1
