---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-sample-app-web
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: k8s-sample-app.example.com
      http:
        paths:
          - backend:
              service: 
                name: k8s-sample-app-web
                port: 
                  number: 3000
