
name: CI to Docker Hub
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      - name: Update docker image in deployment web
        run: 'sed -i "s/{{GIT_TAG}}/${{ github.sha }}/g" "kubernetes_manifests/deploy/02-deployment-web.yaml"'

      - name: Update docker image in tests
        run: 'sed -i "s/{{GIT_TAG}}/${{ github.sha }}/g" "kubernetes_manifests/deploy/03-tests.yaml"'


      - name: Update GIT_TAG environment variable 
        run: 'sed -i "s/{{GIT_TAG}}/${{ github.sha }}/g" "./Dockerfile"'

      - name: Update GIT_AUTHOR environment variable 
        run: 'sed -i "s/{{GIT_AUTHOR}}/${{ github.actor }}/g" "./Dockerfile"'

      - name: Echo manifest file for debugging
        run: 'cat "kubernetes_manifests/deploy/02-deployment-web.yaml"'

      - name: Echo Dockerfile for debugging
        run: 'cat "./Dockerfile"'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ruby_rails_docker:${{ github.sha }}

      - name: Get Kubernetes pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Apply Postgres configs
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes_manifests/postgres

      - name: Apply Pyroscope config
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes_manifests/pyroscope

      - name: Apply Deploy configs
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes_manifests/deploy

      - name: Apply Traefik config
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes_manifests/traefik
